import { Router } from "express";
import { authController } from "../controllers/authController.js";
import { templateController, workflowController } from "../controllers/crudControllers.js";
import { miscController, notificationController } from "../controllers/notificationController.js";
import { asyncHandler } from "../middleware/asyncHandler.js";
import { authenticate, authorize } from "../middleware/auth.js";
import { apiLimiter } from "../middleware/rateLimit.js";
export const router = Router();
router.post("/auth/register", asyncHandler(authController.register));
router.post("/auth/login", asyncHandler(authController.login));
router.post("/auth/refresh", asyncHandler(authController.refresh));
router.use(authenticate, apiLimiter);
router.get("/auth/me", asyncHandler(authController.me));
router.post("/auth/logout", asyncHandler(authController.logout));
router.route("/templates").post(asyncHandler(templateController.create)).get(asyncHandler(templateController.list));
router.post("/templates/preview", asyncHandler(templateController.preview));
router.route("/templates/:id").get(asyncHandler(templateController.get)).put(asyncHandler(templateController.update)).delete(asyncHandler(templateController.remove));
router.route("/workflows").post(asyncHandler(workflowController.create)).get(asyncHandler(workflowController.list));
router.route("/workflows/:id").get(asyncHandler(workflowController.get)).put(asyncHandler(workflowController.update)).delete(asyncHandler(workflowController.remove));
router.post("/notifications/send", asyncHandler(notificationController.send));
router.post("/notifications/schedule", asyncHandler(notificationController.schedule));
router.get("/notifications", asyncHandler(notificationController.list));
router.get("/notifications/:id", asyncHandler(notificationController.get));
router.get("/notifications/:id/attempts", asyncHandler(notificationController.attempts));
router.post("/notifications/:id/retry", asyncHandler(notificationController.retry));
router.post("/notifications/:id/cancel", asyncHandler(notificationController.cancel));
router.get("/preferences", asyncHandler(miscController.preferences));
router.put("/preferences", asyncHandler(miscController.updatePreferences));
router.get("/in-app-notifications", asyncHandler(miscController.inAppList));
router.get("/in-app-notifications/unread-count", asyncHandler(miscController.unread));
router.patch("/in-app-notifications/:id/read", asyncHandler(miscController.readOne));
router.post("/in-app-notifications/read-all", asyncHandler(miscController.readAll));
router.get("/providers", asyncHandler(miscController.providers));
router.post("/providers", authorize("ADMIN"), asyncHandler(miscController.createProvider));
router.get("/analytics/overview", asyncHandler(miscController.overview));
router.get("/analytics/channels", asyncHandler(miscController.channels));
router.get("/analytics/daily", asyncHandler(miscController.daily));
router.get("/analytics/failures", asyncHandler(miscController.failures));
