import cors from "cors";
import express from "express";
import helmet from "helmet";
import { pinoHttp } from "pino-http";
import swaggerUi from "swagger-ui-express";
import mongoose from "mongoose";
import { redis } from "./config/redis.js";
import { env } from "./config/env.js";
import { logger } from "./config/logger.js";
import { router } from "./routes/index.js";
import { errorHandler } from "./middleware/errorHandler.js";
import { metrics } from "./services/metricsService.js";
import { openApiSpec } from "./utils/openapi.js";
export const app = express();
app.use(helmet());
app.use(cors({ origin: env.FRONTEND_URL, credentials: true }));
app.use(express.json({ limit: "1mb" }));
app.use(pinoHttp({ logger }));
app.use((req, res, next) => { const start = Date.now(); res.on("finish", () => { metrics.inc(`http.${req.method}.${res.statusCode}`); metrics.observe("http.latency_ms", Date.now() - start); }); next(); });
app.get("/health", (_req, res) => res.json({ status: "healthy", services: { api: "healthy", mongodb: mongoose.connection.readyState === 1 ? "healthy" : "unhealthy", redis: redis.status === "ready" ? "healthy" : "starting" } }));
app.get("/health/db", (_req, res) => res.status(mongoose.connection.readyState === 1 ? 200 : 503).json({ status: mongoose.connection.readyState === 1 ? "healthy" : "unhealthy" }));
app.get("/health/redis", async (_req, res) => { try { await redis.ping(); res.json({ status: "healthy" }); } catch { res.status(503).json({ status: "unhealthy" }); } });
app.get("/metrics", (_req, res) => res.json(metrics.snapshot()));
app.use("/api/docs", swaggerUi.serve, swaggerUi.setup(openApiSpec));
app.use("/api", router);
app.use(errorHandler);
